In [3]:
import numpy as np

In [4]:
A = np.array([[1,3,-2],[3,5,6],[2,4,3]])

print(A)

[[ 1  3 -2]
 [ 3  5  6]
 [ 2  4  3]]


In [5]:
B = np.array([[5,7,8]])
#transpose B
B = B.T
print(B)

[[5]
 [7]
 [8]]


In [7]:
X = np.linalg.inv(A).dot(B)
print(X)

[[-15.]
 [  8.]
 [  2.]]
